prebuiltapks: Declare relevant LOCAL_OPTIONAL_USES_LIBRARIES
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (prebuilts/prebuiltapks/AccountManager/app-standard-release-unsigned.apk):
		uses-library-not-required:'androidx.window.extensions'		uses-library-not-required:'androidx.window.sidecar'

error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: [com.android.location.provider]
	                 vs. in the manifest: [com.android.location.provider]
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (prebuilts/prebuiltapks/GmsCore/play-services-core-withMapbox-withoutNearby-release-unsigned.apk):
		uses-library:'com.android.location.provider'		uses-library-not-required:'androidx.window.extensions'		uses-library-not-required:'androidx.window.sidecar